U="Siūlau atnaujinti sistemą atskiroje bandomojoje kopijoje, patikrinti krepšelį bei mokėjimus ir tik tada perkelti į tikrą svetainę"
D = {
"raisantas.lt": ("250–350 € + PVM",
 "Pastebėjau, kad raisantas.lt meniu punktai „Kieto kuro katilai“, „Skysto kuro katilai“ ir „Anglies pluošto šildymo kilimėliai“ atidaro „Produktų kategorija nerasta!“. Be to, parduotuvė veikia ant labai senos OpenCart 1.5 versijos.",
 "Siūlau sutvarkyti meniu ir atnaujinti parduotuvės dizainą, kad atrodytų moderniai ir patogiai veiktų telefone, nekeičiant pačios sistemos. Darbas užtruktų apie savaitę, kaina 250–350 € + PVM."),
"enbaterija.lt": ("100–250 € + PVM",
 "Pastebėjau, kad enbaterija.lt telefone rodoma kaip sumažinta kompiuterio versija, tekstą ir mygtukus tenka didinti pirštais. Mobili versija jūsų temoje yra, bet neįsijungia, o dauguma pirkėjų šiandien ateina iš telefono.",
 "Siūlau įjungti ir sutvarkyti mobilią versiją ir patikrinti ją keliuose telefonuose. Darbas užtruktų 1–2 dienas, kaina 100–250 € + PVM."),
"balticmobiles.lt": ("50–100 € + PVM",
 "Pastebėjau, kad balticmobiles.lt kategorijoje „Blackview“ rašo 872 prekės, bet rodomi vien Apple iPhone, o Blackberry, Asus, Microsoft ir eStar kategorijos tuščios. Pirkėjas, ieškantis konkretaus gamintojo, tada eina kitur.",
 "Siūlau sutvarkyti kategorijas ir prekių priskyrimą. Darbas užtruktų pusdienį, kaina 50–100 € + PVM."),
"kosmetikavisiems.lt": ("preliminariai 250–350 € + PVM",
 "Pastebėjau, kad kosmetikavisiems.lt veikia ant OpenCart 1.5, kurios failai datuoti 2014 m. Ši versija nesuderinama su naujomis PHP versijomis, o hostingams senąsias išjungus parduotuvė gali tiesiog nustoti veikti.",
 "Siūlau pritaikyti parduotuvę naujai PHP ir sutvarkyti, kad gerai atrodytų telefone, nekeičiant sistemos ir neperkeliant prekių. Preliminariai 250–350 € + PVM, tikslią kainą pasakysiu peržiūrėjęs."),
"mocca.lt": ("80–120 € + PVM",
 "Pastebėjau, kad mocca.lt neturi tinkamo SSL sertifikato, jis išduotas hostingo domenui, ne jūsų. Naršyklė rodo įspėjimą, kad svetainė nesaugi, todėl dalis pirkėjų išeina, o prisijungimo slaptažodžiai siunčiami nešifruoti.",
 "Siūlau įdiegti tinkamą sertifikatą ir nukreipti visą svetainę į saugų https. Darbas užtruktų dieną, kaina 80–120 € + PVM."),
"darbobatai.lt": ("250–350 € + PVM",
 "Pastebėjau, kad darbobatai.lt veikia ant WordPress 4.9 ir WooCommerce 3.3, apie aštuonerių metų senumo versijų, kurios nebegauna saugumo pataisymų. Be to, Google kategorijas rodo kaip „Darbo batai Archives“.",
 U + ", taip pat sutvarkyti pavadinimus. Darbas užtruktų apie savaitę, kaina 250–350 € + PVM."),
"dazas.lt": ("250–350 € + PVM",
 "Pastebėjau, kad dazas.lt veikia ant WordPress 5.1 iš 2019 m., o Revolution Slider įskiepis dar 4-osios versijos, kurioje yra žinomų saugumo spragų. Be to, parduotuvės pavadinime Google rodo „Elekroninė“.",
 U + ". Darbas užtruktų 3–5 dienas, kaina 250–350 € + PVM."),
"foleta.lt": ("250–350 € + PVM",
 "Pastebėjau, kad foleta.lt veikia ant WordPress 5.1 ir WooCommerce 3.5 iš 2019 m., kurios nebegauna saugumo pataisymų. Be to, kai kurių krosnelių, pvz. ROMOTOP LAREDO T 04, prekės kodas rodomas su dešimtimis „-1-1-1“.",
 U + ", taip pat sutvarkyti prekių kodus. Darbas užtruktų 3–5 dienas, kaina 250–350 € + PVM."),
"korleja.lt": ("250–350 € + PVM",
 "Pastebėjau, kad korleja.lt veikia ant WordPress 4.9 ir WooCommerce 3.4, apie aštuonerių metų versijų be saugumo pataisymų, kurios gali sustoti hostingui atnaujinus PHP. Be to, kategorija „Čiužiniai“ rodo tik „Produktų nerasta“.",
 U + ". Darbas užtruktų 3–5 dienas, kaina 250–350 € + PVM."),
"floravitas.lt": ("preliminariai 350–450 € + PVM",
 "Pastebėjau, kad floravitas.lt veikia ant WooCommerce 2.4 iš 2015 m., kuri nebegauna saugumo pataisymų ir anksčiau ar vėliau nustos veikti su nauja PHP. Be to, pagrindinio puslapio blokas „TIK VILNIUJE“ atidaro „puslapis nerastas“.",
 U + ", taip pat pataisyti neveikiančias nuorodas. Iš tokios senos versijos tai 1–2 savaičių darbas, preliminariai 350–450 € + PVM."),
"geliulanka.lt": ("250–350 € + PVM",
 "Pastebėjau, kad geliulanka.lt, įvedus adresą be https, atsidaro kaip „Nesaugi“ ir nenukreipia į saugią versiją, nors sertifikatą turite. Be to, svetainė veikia ant WordPress 5.4 ir WooCommerce 3.8, kurios nebegauna saugumo pataisymų.",
 "Siūlau sutvarkyti peradresavimą ir atnaujinti sistemą atskiroje bandomojoje kopijoje, patikrinus krepšelį. Darbas užtruktų 3–5 dienas, kaina 250–350 € + PVM."),
"spila.lt": ("250–350 € + PVM",
 "Pastebėjau, kad spila.lt pagrindinio puslapio dienos pasiūlymas su laikmačiu atidaro „puslapis nerastas“, tad prarandami pirkėjai, kurie jau norėjo pirkti. Be to, parduotuvė veikia ant WooCommerce 3.3 iš 2018 m.",
 "Siūlau pataisyti nuorodą ir atnaujinti WooCommerce bei Divi atskiroje bandomojoje kopijoje. Darbas užtruktų 3–5 dienas, kaina 250–350 € + PVM."),
"wilara.lt": ("preliminariai 350–450 € + PVM",
 "Pastebėjau, kad wilara.lt viršuje esantis mygtukas „Prisijungimas“ atidaro klaidos puslapį, tad klientai nepatenka į paskyrą. Be to, svetainė veikia ant WordPress 4.9 ir WooCommerce 3.1 iš 2017 m., kurios nebegauna saugumo pataisymų.",
 "Siūlau sutvarkyti prisijungimą ir atnaujinti sistemą kartu su daugiakalbe dalimi. Darbas užtruktų 1–2 savaites, preliminariai 350–450 € + PVM."),
"v-s.lt": ("100–200 € + PVM",
 "Pastebėjau, kad v-s.lt kategorijų sąraše matosi techninė „Uncategorized @lt“, kuri atidaro tuščią puslapį, pjūklai 54.0 cm³ ir 54.5 cm³ turi tą pačią nuotrauką, o be https svetainė atsidaro kaip „Nesaugi“.",
 "Siūlau visa tai sutvarkyti. Darbas užtruktų 1–2 dienas, kaina 100–200 € + PVM."),
"stabdziudalys.lt": ("100–150 € + PVM",
 "Pastebėjau, kad stabdziudalys.lt prisijungimo langas visas angliškas („Sign in“, „Lost your password?“), parduotuvė Google rodoma kaip „Shop – Stabdžių dalys“, o pagrindiniame puslapyje matosi 2015 m. įrašai „Uncategorized“. Kartu tai atrodo kaip neprižiūrima svetainė.",
 "Siūlau išversti likusius tekstus, sutvarkyti pavadinimus ir pagrindinį puslapį. Darbas užtruktų dieną, kaina 100–150 € + PVM."),
"dviratininkams.lt": ("80–150 € + PVM",
 "Pastebėjau, kad dviratininkams.lt pagrindinis puslapis neturi pavadinimo, o kitų puslapių pavadinimai baigiasi tuščiu dvitaškiu, pvz. „Kontaktai : “. Būtent šį tekstą Google rodo paieškoje kaip nuorodą, todėl svetainė ten atrodo netvarkingai.",
 "Siūlau sutvarkyti pavadinimus ir aprašymus visai svetainei. Darbas užtruktų dieną, kaina 80–150 € + PVM."),
"ofnis.lt": ("100–200 € + PVM",
 "Pastebėjau, kad ofnis.lt pagrindiniame puslapyje vietoj paieškos rodomas tekstas „[aws_search_form]“, slaiderio „Buzil valymo priemonės“ mygtukas atidaro „Puslapis nerastas“, meniu du kartus kartojasi „Paslaugos“, o kainos rodomos „€ 5,548.00“.",
 "Siūlau visa tai sutvarkyti. Darbas užtruktų 1–2 dienas, kaina 100–200 € + PVM."),
"elmega.lt": ("60–120 € + PVM",
 "Pastebėjau, kad elmega.lt šone liko temos krumpliaratis „Panel Tool“, per kurį bet kuris lankytojas gali perjungti parduotuvės spalvas į „christmas“ ar „purple“. Be to, kelios meniu kategorijos tuščios, pvz. „Termosusitraukiančios pirštinės“.",
 "Siūlau tai išjungti ir sutvarkyti meniu. Darbas užtruktų pusdienį, kaina 60–120 € + PVM."),
"viskaszoo.lt": ("60–120 € + PVM",
 "Pastebėjau, kad viskaszoo.lt meniu „Egzotiniams gyvūnams“ beveik visos kategorijos tuščios: „Apšvietimas“, „Šildymas“, „Maistas“ rodo „Šioje kategorijoje nėra prekių“, iš viso radau devynias. Be to, be https svetainė atsidaro kaip „Nesaugi“.",
 "Siūlau sutvarkyti meniu ir nukreipti svetainę į saugų https. Darbas užtruktų pusdienį, kaina 60–120 € + PVM."),
"sildymasjums.lt": ("100–200 € + PVM",
 "Pastebėjau, kad sildymasjums.lt nuorodose lietuviškos raidės tiesiog išmestos: „Vonios įranga“ tapo /vonios-ranga, „dūmtraukiai“ tapo „dmtraukiai“, o tai blogina paiešką Google. Be to, kelios kategorijos tuščios, o be https svetainė atsidaro kaip „Nesaugi“.",
 "Siūlau perrašyti adresus su peradresavimais nuo senų, sutvarkyti kategorijas ir https. Darbas užtruktų 1–2 dienas, kaina 100–200 € + PVM."),
"balduideja.lt": ("80–150 € + PVM",
 "Pastebėjau, kad balduideja.lt meniu kolekcijos „Nature“ ir „Mango“ atidaro „Kategorija nerasta!“, „Atelie“ ir „Čiužiniai“ tušti, o meniu nuorodos veda į nesaugią http versiją. Baldus pirkėjas renkasi atidžiai, tad tokios vietos krenta į akis.",
 "Siūlau sutvarkyti meniu, https ir kainų formatą. Darbas užtruktų dieną, kaina 80–150 € + PVM."),
"senora.lt": ("50–100 € + PVM",
 "Pastebėjau, kad senora.lt nemažai tekstų liko angliškai: tuščiame krepšelyje rašo „It's never too late to fix it :)“, apačioje „Subscribe to our newsletter“, viršuje „Wishlist“ ir „Compare“.",
 "Siūlau išversti viską ir patikrinti visus puslapius. Darbas užtruktų pusdienį, kaina 50–100 € + PVM."),
}
